### ISSUE TITLE
Starter giving errors.

### ISSUE THREAD

**Issue by ohbob** [smakosh/gatsby-starter-i18n#4]
Manual has problems, as `gatsby new https://github.com/smakosh/gatsby-starter-i18n` gives out an error, lacking 1 argument.

Anyways, after installing and trying to launch development server, I get some errors.
`Error: Cannot find module 'gatsby/dist/utils/create-content-digest'`
`error UNHANDLED REJECTION`
`TypeError: Cannot read property 'filter' of undefined`

**Comment by smakosh** [comment]
Checking 👀

**Comment by smakosh** [comment]
Run this `rm -rf node_modules && yarn upgrade` and all should be fixed
